no-permission: '&cУ вас нет прав.'
args: '&cНеправильный ввод команды.'
player-offline: '&cИгрок не найден.'
chunk-force-loaded: '&aЧанк игрока теперь прогружается.'
admin-loaded-your-chunk: '&aЧанк, на котором вы находитесь, теперь будет прогружаться.'
reloaded: '&aКонфиг перезагружен.'